### ISSUE TITLE
You didn't upload image,font files

### ISSUE THREAD

**Issue by thrashland** [michealodwyer26/The-Lost-Scroll-of-Aspic#1]
So you don't want others build this project,bro?

**Comment by michealodwyer26** [comment]
The reason I didn't upload the assets used for this game is, because the tilesets used throughout the game are not free. I could upload the font files, and the free assets, but, as you have mentioned, the game still cannot be built. If you would like to play the game, you can download the executable jar file, and run it; if you want to look at the source code, it is of course here too, but unfortunately, that is as "open source" as the game can be, within the confines of the law.

**Comment by thrashland** [comment]
I see.And why you have a chinese sentence in your bio?I can speak that language.
